name: Push CSS to Project Wallace
description: Update your CSS at projectwallace.com
author: Bart Veneman (ProjectWallace.com)

inputs:
  project-wallace-token:
    description: 'Webhook token of the project on ProjectWallace.com'
    required: true
  css-path:
    description: 'Path to the CSS you want analyzed'
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  color: 'blue'
  icon: 'bar-chart-2'
